### ISSUE TITLE
s3 support?

### ISSUE THREAD

**Issue by tooptoop4** [ing-bank/apache-ranger-s3-plugin#5]
@arempter is AWS S3 supported?

**Comment by arempter** [comment]
Hey,
The question is very wide, so not sure what exactly you are looking for.
In general plugin uses AWS SDK so it should work. There may be problem with url endpoint value when constructing S3 client, sice we use host:port and in AWS you just specify https://region_url. I never tested it.
So in summary it may/will with small update...

Plugin is just one part, allows Ranger to understand S3 format.
You will also need authorizer on application side, which will ask Ranger, if resource to be accessed is allowed by policy

**Comment by tooptoop4** [comment]
have u plugged pyspark into this?
